apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: empplaydb
  POSTGRES_USER: empplay
  POSTGRES_PASSWORD: Password1
  POSTGRES_HOST: postgres-postgresql
  POSTGRES_PORT: "5432"

