micronaut:
  application:
    name: mn-teams
  server:
    port: 8080
jackson:
  bean-introspection-module: true
---
datasources:
  default:
    url: jdbc:postgresql://${MN_POSTGRES_HOST:localhost}:${MN_POSTGRES_PORT:5432}/${MN_POSTGRES_DB:empplay}
    driverClassName: org.postgresql.Driver
    username: ${MN_POSTGRES_USER:empplay}
    password: ${MN_POSTGRES_PASSWORD:Password1}
    schema-generate: NONE
    dialect: Postgres
jpa:
  default:
    properties:
      hbm2ddl:
        auto: none
      database-platform: org.hibernate.dialect.PostgreSQLDialiect
#flyway:
#  datasources:
#    default:
#      locations: classpath:databasemigrations
#consul:
#  client:
#    registration:
#      enabled: true
#    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
