micronaut:
  application:
    name: mn-data
  server:
    port: -1
jackson:
  bean-introspection-module: true
---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    properties:
      hbm2ddl:
        auto: create-drop
flyway:
  datasources:
    default:
      locations: classpath:databasemigrations
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
