micronaut:
  application:
    name: mn-employees
  server:
    port: 8080
jackson:
  bean-introspection-module: true
---
datasources:
  default:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:empplay}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:empplay}
    password: ${POSTGRES_PASSWORD:Password1}
    schema-generate: NONE
    dialect: Postgres
jpa:
  default:
    properties:
      hbm2ddl:
        auto: none
      database-platform: org.hibernate.dialect.PostgreSQLDialiect
redis:
  uri: redis://:${REDIS_PASSWORD:Password1}@${REDIS_HOST:192.168.110.5}
#flyway:
#  datasources:
#    default:
#      locations: classpath:databasemigrations
#consul:
#  client:
#    registration:
#      enabled: true
#    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
