kind: Deployment
apiVersion: apps/v1
metadata:
  name: mn-employees
  namespace: default
  labels:
    app: mn-employees
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mn-employees
  template:
    metadata:
      name: mn-employees
      labels:
        app: mn-employees
    spec:
      containers:
        - name: mn-employees
          image: 'wpfeiffearbfile/mn-employees:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: postgres-config
          imagePullPolicy: Always
      restartPolicy: Always

