kind: Service
apiVersion: v1
metadata:
  name: mn-teams
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: mn-teams
  type: NodePort
  sessionAffinity: None
